# Generated by Django 4.0.4 on 2022-04-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='photo',
        ),
    ]
