# Generated by Django 4.0.4 on 2022-04-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default='null', upload_to='./main/static/files'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default='null', upload_to='./main/static/videos'),
        ),
    ]
